# LEO Satellite Flyby Emulator Configuration
# This file contains all simulation parameters for the LEO flyby emulator

# Ground station location and specifications
ground_station:
  name: "Example Ground Station"
  latitude_deg: 37.7749      # Latitude in degrees (San Francisco)
  longitude_deg: -122.4194   # Longitude in degrees (San Francisco)
  elevation_m: 10            # Ground station elevation above sea level in meters

# Satellite TLE (Two-Line Element) file path
tle_file: "data/tle_example.txt"  # Path to TLE file containing satellite orbital elements

# Signal parameters for communication simulation
signal:
  frequency_hz: 2400000000   # Carrier frequency in Hz (2.4 GHz default)
  tx_power_dbm: 20           # Transmit power in dBm (20 dBm = 100 mW)
  tx_gain_db: 20             # Transmit antenna gain in dB
  rx_gain_db: 20             # Receive antenna gain in dB
  bandwidth_hz: 1000000      # System bandwidth in Hz (1 MHz default)
  system_noise_temp_k: 290   # System noise temperature in Kelvin
  path_loss_exponent: 2.0    # Path loss exponent for atmospheric effects
  snr_threshold_db: 10       # Minimum SNR threshold for signal detection

# Simulation timing parameters
simulation:
  duration_sec: 600          # Total simulation duration in seconds (10 minutes default)
  time_step_sec: 1           # Time step between calculations in seconds

# Antenna tracking parameters
antenna:
  beamwidth_deg: 10          # Antenna beamwidth in degrees (half-power beamwidth)
  slew_rate_deg_s: 5         # Maximum antenna slew rate in degrees per second
  pointing_error_deg: 0.5    # RMS pointing error in degrees 